import {StyleSheet} from 'react-native';

export const COLORS = {
  navy: '#001F63',
  blue: '#1557F5',
  text: '#11131E',
  muted: '#555A70',
  bg: '#F7F8FC',
  border: '#E2E5EE',
  green: '#087A26',
  red: '#D71920',
  orange: '#E85B10',
};

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: COLORS.bg},
  header: {
    height: 76,
    backgroundColor: COLORS.navy,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  headerTitle: {fontSize: 23, fontWeight: '800', color: '#FFFFFF', letterSpacing: 0.2},
  content: {paddingHorizontal: 11, paddingTop: 12, paddingBottom: 22},

  infoBanner: {
    minHeight: 58,
    backgroundColor: '#073FE8',
    borderRadius: 5,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoText: {flex: 1, marginLeft: 12, color: '#FFFFFF', fontSize: 13, lineHeight: 18, fontWeight: '600'},

  periodRow: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 13, marginBottom: 12},
  periodButton: {
    width: '22.8%',
    height: 36,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: '#DDE0E8',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  periodButtonActive: {backgroundColor: COLORS.navy, borderColor: COLORS.navy},
  periodText: {fontSize: 13, fontWeight: '700', color: COLORS.text},
  periodTextActive: {color: '#FFFFFF'},

  statsGrid: {flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between'},
  statCard: {
    width: '49.2%',
    minHeight: 94,
    backgroundColor: '#FFFFFF',
    borderRadius: 7,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOpacity: 0.055,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  iconCircle: {width: 45, height: 45, borderRadius: 23, alignItems: 'center', justifyContent: 'center', marginRight: 9},
  statTextWrap: {flex: 1},
  statLabel: {fontSize: 12, color: COLORS.muted, fontWeight: '500', lineHeight: 16},
  statValue: {fontSize: 24, fontWeight: '900', marginTop: 3, lineHeight: 28},
  statSub: {fontSize: 11, color: COLORS.muted, marginTop: 4, lineHeight: 15},
  statNote: {fontSize: 11, color: COLORS.green, fontWeight: '700'},

  twoColumn: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 2},
  halfCard: {
    width: '49.2%',
    backgroundColor: '#FFFFFF',
    borderRadius: 7,
    paddingHorizontal: 9,
    paddingTop: 11,
    paddingBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.055,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  cardHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8},
  cardTitle: {fontSize: 14, fontWeight: '900', color: COLORS.text},
  headerLink: {fontSize: 11, color: '#003BFF', fontWeight: '700'},

  planRow: {flexDirection: 'row', alignItems: 'center', height: 43, borderBottomWidth: 1, borderBottomColor: '#EEF0F5'},
  planBadge: {width: 63, height: 25, borderRadius: 3, alignItems: 'center', justifyContent: 'center', marginRight: 8},
  planBadgeText: {fontSize: 10, color: '#FFFFFF', fontWeight: '700'},
  planPrice: {fontSize: 11, color: COLORS.text, fontWeight: '800', flex: 1},
  planCompanies: {fontSize: 10, color: COLORS.muted, width: 64},
  createPlan: {fontSize: 13, color: '#003BFF', fontWeight: '600', marginTop: 12},

  chartLegend: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 0, marginBottom: 5},
  legendItem: {flexDirection: 'row', alignItems: 'center', marginHorizontal: 7},
  legendLine: {width: 18, height: 2, marginRight: 5},
  dashedLine: {width: 18, borderTopWidth: 1, borderStyle: 'dashed', marginRight: 5},
  legendText: {fontSize: 8.5, color: '#25283A'},
  chartBox: {height: 137, paddingLeft: 26, paddingRight: 9, paddingTop: 4, paddingBottom: 18, position: 'relative'},
  yLabel: {position: 'absolute', left: 0, fontSize: 9, color: COLORS.muted},
  xLabel: {position: 'absolute', bottom: 0, fontSize: 9, color: COLORS.text},
  gridLine: {position: 'absolute', left: 26, right: 8, height: 1, backgroundColor: '#ECEEF4'},
  trendArea: {position: 'absolute', left: 52, right: 20, bottom: 19, height: 85, backgroundColor: '#EEF7EA', opacity: 0.9},
  chartLine: {position: 'absolute', height: 2, backgroundColor: COLORS.blue},
  expectedLine: {position: 'absolute', borderTopWidth: 1, borderStyle: 'dashed', borderColor: COLORS.orange},
  chartDot: {position: 'absolute', width: 7, height: 7, borderRadius: 4, backgroundColor: COLORS.blue},
  callout: {position: 'absolute', right: 5, top: 3, backgroundColor: COLORS.blue, borderRadius: 3, width: 45, height: 34, alignItems: 'center', justifyContent: 'center'},
  calloutText: {fontSize: 10, lineHeight: 12, color: '#FFFFFF', fontWeight: '800', textAlign: 'center'},

  listCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 7,
    marginTop: 9,
    paddingTop: 11,
    shadowColor: '#000',
    shadowOpacity: 0.055,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
    overflow: 'hidden',
  },
  listHeader: {paddingHorizontal: 11, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  listTitle: {fontSize: 16, fontWeight: '900', color: COLORS.text},
  listLink: {fontSize: 13, color: '#003BFF', fontWeight: '700'},
  subRow: {minHeight: 61, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EEF0F5'},
  avatar: {width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', marginRight: 10},
  avatarText: {color: '#FFFFFF', fontSize: 18, fontWeight: '800'},
  rowMain: {flex: 1, paddingRight: 6},
  rowName: {fontSize: 13, fontWeight: '900', color: COLORS.text},
  rowDesc: {fontSize: 11, color: COLORS.muted, marginTop: 1},
  rowDate: {fontSize: 11, color: COLORS.muted, marginTop: 1},
  redText: {color: COLORS.red},
  orangeText: {color: COLORS.orange},
  statusWrap: {alignItems: 'flex-end', minWidth: 84},
  statusBadge: {height: 22, minWidth: 64, paddingHorizontal: 11, borderRadius: 5, alignItems: 'center', justifyContent: 'center'},
  statusText: {fontSize: 11, fontWeight: '700'},
  outlineButton: {height: 25, minWidth: 96, marginTop: 8, borderRadius: 3, borderWidth: 1, borderColor: '#1557F5', alignItems: 'center', justifyContent: 'center'},
  outlineButtonText: {fontSize: 11, color: '#003BFF', fontWeight: '700'},

  txRow: {minHeight: 54, paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#EEF0F5'},
  txIcon: {width: 28, alignItems: 'flex-start'},
  txCompany: {flex: 1.2},
  txDate: {flex: 0.85, fontSize: 10.5, color: COLORS.muted, textAlign: 'center'},
  txAmount: {width: 70, fontSize: 13, fontWeight: '900', textAlign: 'right'},
  txStatus: {width: 82, alignItems: 'flex-end'},

  actionsRow: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 12},
  actionButton: {width: '49%', height: 44, borderRadius: 5, borderWidth: 1, borderColor: COLORS.navy, alignItems: 'center', justifyContent: 'center', flexDirection: 'row'},
  actionButtonDark: {backgroundColor: COLORS.navy},
  actionButtonText: {fontSize: 13, fontWeight: '700', color: COLORS.navy, marginLeft: 8},
  actionButtonTextDark: {color: '#FFFFFF'},
});
