import {StyleSheet} from 'react-native';
import {colors, fonts, size, dashboardTextSize} from '../../../theme';
export const s = size;
export const fs = dashboardTextSize;

export const makeStyles = () =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: colors.financeBackground,
    },
    header: {
      height: s(76),
      backgroundColor: colors.primary,
      paddingHorizontal: s(30),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitle: {
      color: colors.white,
      fontSize: fs(32),
      fontFamily: fonts.extraBold,
      letterSpacing: s(0.4),
    },
    headerIconButton: {
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
    },
    notificationBox: {
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
    },
    badge: {
      position: 'absolute',
      right: -s(8),
      top: -s(11),
      width: s(31),
      height: s(31),
      borderRadius: s(16),
      backgroundColor: colors.dangerDark,
      alignItems: 'center',
      justifyContent: 'center',
    },
    badgeText: {
      color: colors.white,
      fontSize: fs(15),
      fontFamily: fonts.extraBold,
    },
    body: {
      paddingHorizontal: s(30),
      paddingTop: s(22),
      paddingBottom: s(108),
    },
    welcomeCard: {
      minHeight: s(76),
      backgroundColor: colors.white,
      borderRadius: s(10),
      borderLeftWidth: s(9),
      borderLeftColor: colors.financeBlue,
      paddingHorizontal: s(28),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: colors.black,
      shadowOpacity: 0.06,
      shadowRadius: s(12),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    welcomeTitle: {
      color: colors.text,
      fontSize: fs(24),
      fontFamily: fonts.extraBold,
      letterSpacing: s(0.3),
    },
    welcomeDate: {
      color: colors.slateText,
      fontSize: fs(15),
      fontFamily: fonts.medium,
      letterSpacing: s(0.8),
    },
    sectionHeader: {
      marginTop: s(23),
      marginBottom: s(13),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: s(6),
    },
    sectionTitle: {
      color: colors.text,
      fontSize: fs(24),
      fontFamily: fonts.extraBold,
    },
    sectionAction: {
      color: colors.financeBlue,
      fontSize: fs(18),
      fontFamily: fonts.bold,
    },
    totalCard: {
      minHeight: s(150),
      backgroundColor: colors.white,
      borderRadius: s(10),
      paddingHorizontal: s(30),
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.055,
      shadowRadius: s(10),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    totalIconBox: {
      width: s(130),
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    overviewGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: s(14),
    },
    overviewSmallCard: {
      width: '49%',
      minHeight: s(120),
      backgroundColor: colors.white,
      borderRadius: s(10),
      paddingHorizontal: s(14),
      paddingVertical: s(12),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: s(13),
      shadowColor: colors.black,
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    overviewIconCircle: {
      width: s(66),
      height: s(66),
      borderRadius: s(33),
      alignItems: 'center',
      justifyContent: 'center',
    },
    overviewTextBox: {
      flex: 1,
      minWidth: 0,
      marginLeft: s(14),
    },
    totalTextBox: {
      marginLeft: s(3),
    },
    overviewTitle: {
      color: colors.slateText,
      fontSize: fs(16),
      fontFamily: fonts.medium,
      lineHeight: fs(19),
    },
    overviewValue: {
      color: colors.text,
      fontSize: fs(30),
      fontFamily: fonts.extraBold,
      lineHeight: fs(36),
      marginTop: s(2),
      letterSpacing: s(0.5),
    },
    totalOverviewValue: {
      fontSize: fs(42),
      lineHeight: fs(48),
    },
    overviewSub: {
      color: colors.slateText,
      fontSize: fs(15),
      fontFamily: fonts.medium,
      lineHeight: fs(18),
      marginTop: s(0),
    },
    greenText: {
      color: colors.success,
    },
    redText: {
      color: colors.dangerDark,
    },
    twoColumnRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: s(0),
    },
    halfCard: {
      width: '100%',
      backgroundColor: colors.white,
      borderRadius: s(10),
      paddingHorizontal: s(18),
      paddingTop: s(18),
      paddingBottom: s(17),
      shadowColor: colors.black,
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    cardTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    cardTitle: {
      color: colors.text,
      fontSize: fs(24),
      fontFamily: fonts.extraBold,
    },
    healthBadge: {
      minWidth: s(74),
      height: s(32),
      borderRadius: s(16),
      backgroundColor: colors.success,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: s(14),
    },
    healthBadgeText: {
      color: colors.white,
      fontSize: fs(14),
      fontFamily: fonts.extraBold,
    },
    healthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: s(24),
    },
    healthLabel: {
      width: s(150),
      color: colors.dashboardHealthText,
      fontSize: fs(15),
      fontFamily: fonts.medium,
    },
    healthTrack: {
      flex: 1,
      height: s(10),
      borderRadius: s(8),
      backgroundColor: colors.dealerProgressTrack,
      overflow: 'hidden',
    },
    healthFill: {
      height: s(10),
      borderRadius: s(8),
    },
    healthValue: {
      width: s(54),
      textAlign: 'right',
      fontSize: fs(14),
      fontFamily: fonts.extraBold,
    },
    cleanRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      marginTop: s(8),
    },
    cleanText: {
      color: colors.success,
      fontSize: fs(15),
      fontFamily: fonts.extraBold,
      marginLeft: s(5),
    },
    revenueInfoText: {
      color: colors.slateText,
      fontSize: fs(14),
      fontStyle: 'italic',
      fontFamily: fonts.medium,
      lineHeight: fs(20),
      marginTop: s(13),
    },
    revenueLabel: {
      color: colors.dashboardRevenueText,
      fontSize: fs(14),
      fontFamily: fonts.medium,
      marginTop: s(28),
    },
    revenueAmount: {
      color: colors.financeBlue,
      fontSize: fs(33),
      fontFamily: fonts.extraBold,
      marginTop: s(4),
    },
    revenueStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: s(19),
    },
    revenueMiniBox: {
      width: '31%',
      minHeight: s(58),
      borderRadius: s(6),
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: s(6),
    },
    revenueMiniLabel: {
      fontSize: fs(15),
      fontFamily: fonts.bold,
      textAlign: 'center',
    },
    revenueMiniValue: {
      fontSize: fs(18),
      fontFamily: fonts.extraBold,
      marginTop: s(2),
      textAlign: 'center',
    },
    attentionCard: {
      backgroundColor: colors.white,
      borderRadius: s(10),
      marginTop: s(13),
      paddingTop: s(17),
      paddingBottom: s(7),
      shadowColor: colors.black,
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    attentionHeader: {
      paddingHorizontal: s(18),
      paddingBottom: s(10),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    attentionTitle: {
      color: colors.text,
      fontSize: fs(24),
      fontFamily: fonts.extraBold,
    },
    attentionBadge: {
      width: s(28),
      height: s(28),
      borderRadius: s(14),
      backgroundColor: colors.dangerDark,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attentionBadgeText: {
      color: colors.white,
      fontSize: fs(15),
      fontFamily: fonts.extraBold,
    },
    attentionRow: {
      minHeight: s(61),
      flexDirection: 'row',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: colors.financeDivider,
      paddingHorizontal: s(22),
    },
    attentionColorBar: {
      position: 'absolute',
      left: s(10),
      top: 0,
      bottom: 0,
      width: s(4),
    },
    attentionIconCircle: {
      width: s(38),
      height: s(38),
      borderRadius: s(19),
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: s(8),
      marginRight: s(22),
    },
    attentionTextBox: {
      flex: 1,
      minWidth: 0,
    },
    attentionItemTitle: {
      color: colors.text,
      fontSize: fs(18),
      fontFamily: fonts.extraBold,
      lineHeight: fs(22),
    },
    attentionItemSub: {
      color: colors.slateText,
      fontSize: fs(16),
      fontFamily: fonts.medium,
      lineHeight: fs(20),
    },
    attentionButton: {
      width: s(146),
      height: s(36),
      borderRadius: s(4),
      borderWidth: 1,
      borderColor: colors.financeBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attentionButtonText: {
      color: colors.financeBlue,
      fontSize: fs(16),
      fontFamily: fonts.bold,
    },
    companyCard: {
      minHeight: s(82),
      backgroundColor: colors.white,
      borderRadius: s(10),
      paddingLeft: s(18),
      paddingRight: s(22),
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.financeDivider,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: s(8),
      shadowOffset: {width: 0, height: s(1)},
      elevation: 1,
    },
    companyAvatar: {
      width: s(62),
      height: s(62),
      borderRadius: s(31),
      alignItems: 'center',
      justifyContent: 'center',
    },
    companyAvatarText: {
      color: colors.white,
      fontSize: fs(25),
      fontFamily: fonts.extraBold,
    },
    companyInfo: {
      flex: 1,
      minWidth: 0,
      marginLeft: s(18),
    },
    companyName: {
      color: colors.text,
      fontSize: fs(20),
      fontFamily: fonts.extraBold,
      lineHeight: fs(23),
    },
    companyOwner: {
      color: colors.slateText,
      fontSize: fs(18),
      fontFamily: fonts.medium,
      marginTop: s(2),
      lineHeight: fs(18),
    },
    locationRow: {
      marginTop: s(1),
      flexDirection: 'row',
      alignItems: 'center',
    },
    companyLocation: {
      color: colors.slateText,
      fontSize: fs(18),
      fontFamily: fonts.medium,
      marginLeft: s(4),
      lineHeight: fs(18),
    },
    companyRight: {
      width: s(140),
      alignItems: 'flex-start',
      marginRight: s(12),
    },
    statusPill: {
      minWidth: s(72),
      height: s(30),
      borderRadius: s(13),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      marginLeft: s(20),
    },
    statusText: {
      fontSize: fs(16),
      fontFamily: fonts.bold,
    },
    planText: {
      color: colors.financeBlue,
      fontSize: fs(12),
      fontFamily: fonts.extraBold,
      marginTop: s(3),
    },
    addedText: {
      color: colors.slateText,
      fontSize: fs(13),
      fontFamily: fonts.medium,
      lineHeight: fs(18),
    },
    broadcastCard: {
      backgroundColor: colors.white,
      borderRadius: s(10),
      marginTop: s(12),
      paddingHorizontal: s(20),
      paddingTop: s(15),
      paddingBottom: s(16),
      shadowColor: colors.black,
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    broadcastTitle: {
      color: colors.text,
      fontSize: fs(24),
      fontFamily: fonts.extraBold,
      marginBottom: s(12),
    },
    broadcastButton: {
      height: s(42),
      borderWidth: 1,
      borderColor: colors.financeBlue,
      borderRadius: s(4),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    broadcastText: {
      color: colors.financeBlue,
      fontSize: fs(24),
      fontFamily: fonts.medium,
      marginLeft: s(10),
    },
    nav: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: s(89),
      backgroundColor: colors.white,
      borderTopLeftRadius: s(25),
      borderTopRightRadius: s(25),
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: s(30),
      shadowColor: colors.black,
      shadowOpacity: 0.08,
      shadowRadius: s(18),
      shadowOffset: {width: 0, height: -s(3)},
      elevation: 14,
    },
    tab: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: s(95),
    },
    tabLabel: {
      marginTop: s(5),
      color: colors.dashboardTabMuted,
      fontSize: fs(16),
      fontFamily: fonts.medium,
    },
    tabActive: {
      color: colors.financeBlue,
      fontFamily: fonts.extraBold,
    },
  });
