import {Dimensions, StyleSheet} from 'react-native';
import {C} from './constants/dashboardTheme';

const BASE_WIDTH = 832;
const {width} = Dimensions.get('window');
const ratio = width / BASE_WIDTH;

export const s = (value: number) => Math.round(value * ratio);
export const fs = (value: number) =>
  Math.max(9, Math.round(value * ratio * 1.08));

export const makeStyles = () =>
  StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: C.bg,
    },
    header: {
      height: s(76),
      backgroundColor: C.navy,
      paddingHorizontal: s(30),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    headerTitle: {
      color: C.white,
      fontSize: fs(32),
      fontWeight: '900',
      letterSpacing: s(0.4),
    },
    headerIconButton: {
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
    },
    notificationBox: {
      width: s(44),
      height: s(44),
      alignItems: 'center',
      justifyContent: 'center',
    },
    badge: {
      position: 'absolute',
      right: -s(8),
      top: -s(11),
      width: s(31),
      height: s(31),
      borderRadius: s(16),
      backgroundColor: C.red,
      alignItems: 'center',
      justifyContent: 'center',
    },
    badgeText: {
      color: C.white,
      fontSize: fs(15),
      fontWeight: '900',
    },
    body: {
      paddingHorizontal: s(30),
      paddingTop: s(22),
      paddingBottom: s(108),
    },
    welcomeCard: {
      minHeight: s(76),
      backgroundColor: C.white,
      borderRadius: s(10),
      borderLeftWidth: s(9),
      borderLeftColor: C.blue,
      paddingHorizontal: s(28),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: s(12),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    welcomeTitle: {
      color: C.text,
      fontSize: fs(28),
      fontWeight: '900',
      letterSpacing: s(0.3),
    },
    welcomeDate: {
      color: C.muted,
      fontSize: fs(15),
      fontWeight: '500',
      letterSpacing: s(0.8),
    },
    sectionHeader: {
      marginTop: s(23),
      marginBottom: s(13),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: s(6),
    },
    sectionTitle: {
      color: C.text,
      fontSize: fs(24),
      fontWeight: '900',
    },
    sectionAction: {
      color: C.linkBlue,
      fontSize: fs(18),
      fontWeight: '700',
    },
    totalCard: {
      minHeight: s(150),
      backgroundColor: C.white,
      borderRadius: s(10),
      paddingHorizontal: s(30),
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.055,
      shadowRadius: s(10),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    totalIconBox: {
      width: s(130),
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    overviewGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: s(14),
    },
    overviewSmallCard: {
      width: '49%',
      minHeight: s(120),
      backgroundColor: C.white,
      borderRadius: s(10),
      paddingHorizontal: s(20),
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: s(13),
      shadowColor: '#000',
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    overviewIconCircle: {
      width: s(76),
      height: s(76),
      borderRadius: s(38),
      alignItems: 'center',
      justifyContent: 'center',
    },
    overviewTextBox: {
      flex: 1,
      marginLeft: s(22),
    },
    totalTextBox: {
      marginLeft: s(3),
    },
    overviewTitle: {
      color: C.muted,
      fontSize: fs(20),
      fontWeight: '500',
      lineHeight: fs(21),
    },
    overviewValue: {
      color: C.text,
      fontSize: fs(41),
      fontWeight: '900',
      lineHeight: fs(49),
      marginTop: s(2),
    },
    totalOverviewValue: {
      fontSize: fs(54),
      lineHeight: fs(62),
    },
    overviewSub: {
      color: C.muted,
      fontSize: fs(19),
      fontWeight: '500',
      lineHeight: fs(20),
      marginTop: s(0),
    },
    greenText: {
      color: C.green,
    },
    redText: {
      color: C.red,
    },
    twoColumnRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: s(0),
    },
    halfCard: {
      width: '100%',
      backgroundColor: C.white,
      borderRadius: s(10),
      paddingHorizontal: s(18),
      paddingTop: s(18),
      paddingBottom: s(17),
      shadowColor: '#000',
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    cardTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    cardTitle: {
      color: C.text,
      fontSize: fs(24),
      fontWeight: '900',
    },
    healthBadge: {
      minWidth: s(74),
      height: s(32),
      borderRadius: s(16),
      backgroundColor: C.green,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: s(14),
    },
    healthBadgeText: {
      color: C.white,
      fontSize: fs(14),
      fontWeight: '800',
    },
    healthRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: s(24),
    },
    healthLabel: {
      width: s(150),
      color: '#1D2030',
      fontSize: fs(15),
      fontWeight: '500',
    },
    healthTrack: {
      flex: 1,
      height: s(10),
      borderRadius: s(8),
      backgroundColor: C.track,
      overflow: 'hidden',
    },
    healthFill: {
      height: s(10),
      borderRadius: s(8),
    },
    healthValue: {
      width: s(54),
      textAlign: 'right',
      fontSize: fs(14),
      fontWeight: '900',
    },
    cleanRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      marginTop: s(8),
    },
    cleanText: {
      color: C.green,
      fontSize: fs(15),
      fontWeight: '800',
      marginLeft: s(5),
    },
    revenueInfoText: {
      color: C.muted,
      fontSize: fs(14),
      fontStyle: 'italic',
      fontWeight: '500',
      lineHeight: fs(20),
      marginTop: s(13),
    },
    revenueLabel: {
      color: '#33364A',
      fontSize: fs(14),
      fontWeight: '500',
      marginTop: s(28),
    },
    revenueAmount: {
      color: C.blue,
      fontSize: fs(33),
      fontWeight: '900',
      marginTop: s(4),
    },
    revenueStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: s(19),
    },
    revenueMiniBox: {
      width: '31%',
      minHeight: s(58),
      borderRadius: s(6),
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    revenueMiniLabel: {
      fontSize: fs(22),
      fontWeight: '700',
    },
    revenueMiniValue: {
      fontSize: fs(24),
      fontWeight: '900',
      marginTop: s(2),
    },
    attentionCard: {
      backgroundColor: C.white,
      borderRadius: s(10),
      marginTop: s(13),
      paddingTop: s(17),
      paddingBottom: s(7),
      shadowColor: '#000',
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    attentionHeader: {
      paddingHorizontal: s(18),
      paddingBottom: s(10),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    attentionTitle: {
      color: C.text,
      fontSize: fs(24),
      fontWeight: '900',
    },
    attentionBadge: {
      width: s(28),
      height: s(28),
      borderRadius: s(14),
      backgroundColor: C.red,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attentionBadgeText: {
      color: C.white,
      fontSize: fs(15),
      fontWeight: '900',
    },
    attentionRow: {
      minHeight: s(61),
      flexDirection: 'row',
      alignItems: 'center',
      borderTopWidth: 1,
      borderTopColor: C.border,
      paddingHorizontal: s(22),
    },
    attentionColorBar: {
      position: 'absolute',
      left: s(10),
      top: 0,
      bottom: 0,
      width: s(4),
    },
    attentionIconCircle: {
      width: s(38),
      height: s(38),
      borderRadius: s(19),
      alignItems: 'center',
      justifyContent: 'center',
      marginLeft: s(8),
      marginRight: s(22),
    },
    attentionTextBox: {
      flex: 1,
    },
    attentionItemTitle: {
      color: C.text,
      fontSize: fs(18),
      fontWeight: '900',
      lineHeight: fs(22),
    },
    attentionItemSub: {
      color: C.muted,
      fontSize: fs(16),
      fontWeight: '500',
      lineHeight: fs(20),
    },
    attentionButton: {
      width: s(146),
      height: s(36),
      borderRadius: s(4),
      borderWidth: 1,
      borderColor: C.linkBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    attentionButtonText: {
      color: C.linkBlue,
      fontSize: fs(16),
      fontWeight: '700',
    },
    companyCard: {
      minHeight: s(82),
      backgroundColor: C.white,
      borderRadius: s(10),
      paddingLeft: s(18),
      paddingRight: s(22),
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: C.border,
      shadowColor: '#000',
      shadowOpacity: 0.04,
      shadowRadius: s(8),
      shadowOffset: {width: 0, height: s(1)},
      elevation: 1,
    },
    companyAvatar: {
      width: s(62),
      height: s(62),
      borderRadius: s(31),
      alignItems: 'center',
      justifyContent: 'center',
    },
    companyAvatarText: {
      color: C.white,
      fontSize: fs(25),
      fontWeight: '900',
    },
    companyInfo: {
      flex: 1,
      marginLeft: s(24),
    },
    companyName: {
      color: C.text,
      fontSize: fs(20),
      fontWeight: '900',
      lineHeight: fs(23),
    },
    companyOwner: {
      color: C.muted,
      fontSize: fs(18),
      fontWeight: '500',
      marginTop: s(2),
      lineHeight: fs(18),
    },
    locationRow: {
      marginTop: s(1),
      flexDirection: 'row',
      alignItems: 'center',
    },
    companyLocation: {
      color: C.muted,
      fontSize: fs(18),
      fontWeight: '500',
      marginLeft: s(4),
      lineHeight: fs(18),
    },
    companyRight: {
      width: s(160),
      alignItems: 'flex-start',
      marginRight: s(18),
    },
    statusPill: {
      minWidth: s(72),
      height: s(30),
      borderRadius: s(13),
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      marginLeft: s(20),
    },
    statusText: {
      fontSize: fs(16),
      fontWeight: '700',
    },
    planText: {
      color: C.linkBlue,
      fontSize: fs(12),
      fontWeight: '800',
      marginTop: s(3),
    },
    addedText: {
      color: C.muted,
      fontSize: fs(13),
      fontWeight: '500',
      lineHeight: fs(18),
    },
    broadcastCard: {
      backgroundColor: C.white,
      borderRadius: s(10),
      marginTop: s(12),
      paddingHorizontal: s(20),
      paddingTop: s(15),
      paddingBottom: s(16),
      shadowColor: '#000',
      shadowOpacity: 0.055,
      shadowRadius: s(9),
      shadowOffset: {width: 0, height: s(2)},
      elevation: 2,
    },
    broadcastTitle: {
      color: C.text,
      fontSize: fs(24),
      fontWeight: '900',
      marginBottom: s(12),
    },
    broadcastButton: {
      height: s(42),
      borderWidth: 1,
      borderColor: C.linkBlue,
      borderRadius: s(4),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    broadcastText: {
      color: C.linkBlue,
      fontSize: fs(24),
      fontWeight: '500',
      marginLeft: s(10),
    },
    nav: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: s(89),
      backgroundColor: C.white,
      borderTopLeftRadius: s(25),
      borderTopRightRadius: s(25),
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: s(30),
      shadowColor: '#000',
      shadowOpacity: 0.08,
      shadowRadius: s(18),
      shadowOffset: {width: 0, height: -s(3)},
      elevation: 14,
    },
    tab: {
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: s(95),
    },
    tabLabel: {
      marginTop: s(5),
      color: '#686A82',
      fontSize: fs(16),
      fontWeight: '500',
    },
    tabActive: {
      color: C.linkBlue,
      fontWeight: '800',
    },
  });
