import {Dimensions, StyleSheet} from 'react-native';

const {width} = Dimensions.get('window');
const BASE_WIDTH = 393;
const scale = Math.min(width / BASE_WIDTH, 1);
const s = (value: number) => Math.round(value * scale);

export const COLORS = {
  navy: '#001F63',
  blue: '#1557F5',
  text: '#11131E',
  muted: '#555A70',
  line: '#E7E8EF',
  bg: '#F7F8FC',
  white: '#FFFFFF',
  green: '#0B8E2A',
  red: '#E51B2B',
  orange: '#F15A24',
};

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: COLORS.bg},

  header: {
    height: s(59),
    backgroundColor: COLORS.navy,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: s(14),
  },
  headerTitle: {
    fontSize: s(20),
    color: COLORS.white,
    fontWeight: '800',
    letterSpacing: 0.2,
  },

  content: {
    paddingHorizontal: s(9),
    paddingTop: s(7),
    paddingBottom: s(14),
  },

  hero: {
    backgroundColor: COLORS.navy,
    borderRadius: s(6),
    alignItems: 'center',
    paddingTop: s(7),
    paddingBottom: s(8),
    marginBottom: s(7),
  },
  avatarWrap: {
    width: s(92),
    height: s(92),
    borderRadius: s(46),
    borderWidth: s(2),
    borderColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: COLORS.white,
    fontSize: s(38),
    fontWeight: '800',
    letterSpacing: 3,
  },
  camera: {
    width: s(31),
    height: s(31),
    borderRadius: s(16),
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: s(-8),
    bottom: s(-1),
  },
  heroName: {
    fontSize: s(21),
    fontWeight: '800',
    color: COLORS.white,
    marginTop: s(6),
    lineHeight: s(25),
  },
  heroRole: {
    fontSize: s(11),
    color: COLORS.white,
    fontWeight: '700',
    marginTop: s(1),
  },
  heroChip: {
    minWidth: s(156),
    height: s(22),
    borderRadius: s(7),
    borderWidth: 1,
    borderColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: s(6),
    paddingHorizontal: s(9),
  },
  heroChipText: {
    fontSize: s(11),
    color: COLORS.white,
    fontWeight: '700',
  },
  heroMember: {
    fontSize: s(10.5),
    color: COLORS.white,
    marginTop: s(5),
  },

  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },

  card: {
    width: '49%',
    backgroundColor: COLORS.white,
    borderRadius: s(6),
    paddingHorizontal: s(8),
    paddingTop: s(8),
    paddingBottom: s(7),
    marginBottom: s(6),
    shadowColor: '#000',
    shadowOpacity: 0.055,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  cardFull: {
    backgroundColor: COLORS.white,
    borderRadius: s(6),
    paddingHorizontal: s(8),
    paddingTop: s(8),
    paddingBottom: s(7),
    marginBottom: s(6),
    shadowColor: '#000',
    shadowOpacity: 0.055,
    shadowRadius: 7,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: s(6),
  },
  cardTitle: {
    fontSize: s(14.5),
    fontWeight: '900',
    color: COLORS.text,
    lineHeight: s(18),
  },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: s(25),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  lastRow: {borderBottomWidth: 0},
  rowIcon: {width: s(21), alignItems: 'flex-start'},
  label: {
    flex: 1,
    fontSize: s(8.7),
    color: COLORS.muted,
    lineHeight: s(12),
  },
  value: {
    fontSize: s(9.2),
    fontWeight: '800',
    color: COLORS.text,
    maxWidth: '50%',
    lineHeight: s(12),
  },
  note: {
    fontSize: s(8),
    color: COLORS.green,
    marginLeft: s(4),
    fontWeight: '700',
  },
  highlight: {color: '#003BFF'},

  logoBox: {
    width: s(132),
    height: s(103),
    borderRadius: s(12),
    borderWidth: 1,
    borderColor: '#DADCE6',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: s(3),
  },
  logoMark: {fontSize: s(36), color: COLORS.blue, fontWeight: '900'},
  logoText: {
    fontSize: s(20),
    color: COLORS.navy,
    fontWeight: '800',
    marginTop: s(2),
  },
  tapText: {
    fontSize: s(9.5),
    color: COLORS.muted,
    textAlign: 'center',
    marginTop: s(7),
  },
  outlineBtn: {
    height: s(27),
    borderWidth: 1,
    borderColor: '#003BFF',
    borderRadius: s(4),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: s(7),
    alignSelf: 'center',
    width: s(132),
  },
  outlineBtnText: {fontSize: s(10.5), color: '#003BFF', fontWeight: '800'},

  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: s(30),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  itemTextWrap: {flex: 1},
  itemTitle: {
    fontSize: s(10.2),
    fontWeight: '800',
    color: COLORS.text,
    lineHeight: s(13),
  },
  itemSubtitle: {
    fontSize: s(8.8),
    color: COLORS.muted,
    marginTop: s(1),
    lineHeight: s(11),
  },
  itemValue: {
    fontSize: s(8.8),
    color: '#003BFF',
    marginRight: s(5),
    lineHeight: s(11),
  },

  switch: {
    width: s(31),
    height: s(18),
    borderRadius: s(11),
    padding: s(2),
    justifyContent: 'center',
  },
  switchOn: {backgroundColor: '#1557F5', alignItems: 'flex-end'},
  switchOff: {backgroundColor: '#C9CCD6', alignItems: 'flex-start'},
  switchKnob: {width: s(14), height: s(14), borderRadius: s(7), backgroundColor: COLORS.white},

  loginRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: s(6),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  loginDot: {
    width: s(6),
    height: s(6),
    borderRadius: s(3),
    marginTop: s(5),
    marginRight: s(8),
  },
  loginContent: {
    flex: 1,
    minWidth: 0,
    paddingRight: s(5),
  },
  loginDevice: {
    fontSize: s(10),
    fontWeight: '800',
    color: COLORS.text,
    lineHeight: s(13),
  },
  loginLocation: {
    fontSize: s(8.5),
    color: COLORS.muted,
    marginTop: s(1),
    lineHeight: s(11),
  },
  loginRight: {
    width: s(88),
    alignItems: 'flex-end',
    flexShrink: 0,
  },
  loginTime: {
    fontSize: s(8.2),
    color: COLORS.muted,
    lineHeight: s(11),
    textAlign: 'right',
  },
  blocked: {color: COLORS.red},
  reviewBtn: {
    height: s(23),
    minWidth: s(59),
    borderRadius: s(4),
    borderWidth: 1,
    borderColor: '#003BFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: s(5),
    paddingHorizontal: s(7),
  },
  reviewText: {fontSize: s(8.8), color: '#003BFF', fontWeight: '800'},

  alertBox: {
    borderWidth: 1,
    borderColor: '#FDBA74',
    backgroundColor: '#FFF7ED',
    borderRadius: s(5),
    padding: s(8),
    flexDirection: 'row',
    alignItems: 'center',
  },
  alertTextWrap: {flex: 1, marginLeft: s(8)},
  alertTitle: {fontSize: s(9.6), color: COLORS.orange, fontWeight: '900', lineHeight: s(12)},
  alertSubtitle: {fontSize: s(8.4), color: COLORS.muted, marginTop: s(2), lineHeight: s(11)},

  redSide: {borderLeftWidth: s(4), borderLeftColor: COLORS.red},
  dangerNote: {
    fontSize: s(9),
    color: COLORS.red,
    marginTop: s(-2),
    marginBottom: s(5),
    fontWeight: '700',
  },
  actionBtn: {
    height: s(25),
    minWidth: s(54),
    borderRadius: s(4),
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {fontSize: s(8.8), fontWeight: '800'},

  adminRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: s(6),
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  miniAvatar: {
    width: s(30),
    height: s(30),
    borderRadius: s(15),
    backgroundColor: COLORS.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: s(8),
  },
  miniAvatarText: {fontSize: s(14), color: COLORS.white, fontWeight: '800'},
  adminName: {fontSize: s(10.2), fontWeight: '800', color: COLORS.text, lineHeight: s(13)},
  adminRole: {fontSize: s(8.6), color: '#003BFF', fontWeight: '700', marginTop: s(1)},
  statusPill: {
    height: s(21),
    minWidth: s(52),
    borderRadius: s(8),
    backgroundColor: '#EAF7EC',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: s(7),
  },
  statusText: {fontSize: s(8.8), color: COLORS.green, fontWeight: '800'},
  manageBtn: {
    height: s(25),
    minWidth: s(53),
    borderRadius: s(4),
    borderWidth: 1,
    borderColor: '#003BFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  manageText: {fontSize: s(9), color: '#003BFF', fontWeight: '800'},
  addAvatar: {backgroundColor: '#E5E7EB'},
  addText: {fontSize: s(27), color: COLORS.text, fontWeight: '300', marginTop: s(-4)},

  broadcastBtn: {
    height: s(29),
    borderWidth: 1,
    borderColor: '#003BFF',
    borderRadius: s(4),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  broadcastText: {fontSize: s(10.5), color: '#003BFF', fontWeight: '800', marginLeft: s(6)},

  logout: {
    height: s(30),
    borderWidth: 1,
    borderColor: COLORS.red,
    borderRadius: s(4),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginHorizontal: s(3),
    marginBottom: s(4),
  },
  logoutText: {fontSize: s(13), color: COLORS.red, fontWeight: '800', marginLeft: s(8)},
  version: {fontSize: s(10), color: COLORS.muted, textAlign: 'center'},
});
